2015-07-06 03:42:13,090 ERROR: Error syncing package: w3af-api-client@1620350
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 44, in get
    r.raise_for_status()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
2015-07-06 03:42:13,090 ERROR: Error syncing package: w3af-api-client@1620350
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 44, in get
    r.raise_for_status()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
2015-07-12 00:42:06,477 ERROR: Stale serial for package PyUtilib
2015-07-12 00:42:06,477 ERROR: Stale serial for package PyUtilib
2015-07-12 00:42:12,210 ERROR: Stale serial for package PyUtilib
2015-07-12 00:42:12,210 ERROR: Stale serial for package PyUtilib
2015-07-12 00:42:14,561 ERROR: Stale serial for package PyUtilib
2015-07-12 00:42:14,561 ERROR: Stale serial for package PyUtilib
2015-07-12 00:42:14,564 ERROR: Stale serial for PyUtilib (1629152) not updating. Giving up.
2015-07-12 00:42:14,564 ERROR: Stale serial for PyUtilib (1629152) not updating. Giving up.
2015-07-13 03:42:19,031 ERROR: Error syncing package: tesseract@1630237
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-13 03:42:19,031 ERROR: Error syncing package: tesseract@1630237
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-15 05:42:16,886 ERROR: Error syncing package: w3af-api-client@1633556
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 44, in get
    r.raise_for_status()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
2015-07-15 05:42:16,886 ERROR: Error syncing package: w3af-api-client@1633556
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 44, in get
    r.raise_for_status()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
2015-07-15 23:42:15,182 ERROR: Stale serial for package mammoth
2015-07-15 23:42:15,182 ERROR: Stale serial for package mammoth
2015-07-15 23:42:20,965 ERROR: Stale serial for package mammoth
2015-07-15 23:42:20,965 ERROR: Stale serial for package mammoth
2015-07-15 23:42:23,683 ERROR: Stale serial for package mammoth
2015-07-15 23:42:23,683 ERROR: Stale serial for package mammoth
2015-07-15 23:42:23,686 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-15 23:42:23,686 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 00:42:04,144 ERROR: Stale serial for package mammoth
2015-07-16 00:42:04,144 ERROR: Stale serial for package mammoth
2015-07-16 00:42:06,168 ERROR: Stale serial for package mammoth
2015-07-16 00:42:06,168 ERROR: Stale serial for package mammoth
2015-07-16 00:42:09,192 ERROR: Stale serial for package mammoth
2015-07-16 00:42:09,192 ERROR: Stale serial for package mammoth
2015-07-16 00:42:09,194 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 00:42:09,194 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 01:42:03,993 ERROR: Stale serial for package mammoth
2015-07-16 01:42:03,993 ERROR: Stale serial for package mammoth
2015-07-16 01:42:06,007 ERROR: Stale serial for package mammoth
2015-07-16 01:42:06,007 ERROR: Stale serial for package mammoth
2015-07-16 01:42:08,691 ERROR: Stale serial for package mammoth
2015-07-16 01:42:08,691 ERROR: Stale serial for package mammoth
2015-07-16 01:42:08,693 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 01:42:08,693 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 02:42:04,064 ERROR: Stale serial for package mammoth
2015-07-16 02:42:04,064 ERROR: Stale serial for package mammoth
2015-07-16 02:42:06,078 ERROR: Stale serial for package mammoth
2015-07-16 02:42:06,078 ERROR: Stale serial for package mammoth
2015-07-16 02:42:08,765 ERROR: Stale serial for package mammoth
2015-07-16 02:42:08,765 ERROR: Stale serial for package mammoth
2015-07-16 02:42:08,767 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 02:42:08,767 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 03:42:03,600 ERROR: Stale serial for package mammoth
2015-07-16 03:42:03,600 ERROR: Stale serial for package mammoth
2015-07-16 03:42:05,618 ERROR: Stale serial for package mammoth
2015-07-16 03:42:05,618 ERROR: Stale serial for package mammoth
2015-07-16 03:42:08,681 ERROR: Stale serial for package mammoth
2015-07-16 03:42:08,681 ERROR: Stale serial for package mammoth
2015-07-16 03:42:08,683 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 03:42:08,683 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 04:42:03,554 ERROR: Stale serial for package mammoth
2015-07-16 04:42:03,554 ERROR: Stale serial for package mammoth
2015-07-16 04:42:05,556 ERROR: Stale serial for package mammoth
2015-07-16 04:42:05,556 ERROR: Stale serial for package mammoth
2015-07-16 04:42:08,559 ERROR: Stale serial for package mammoth
2015-07-16 04:42:08,559 ERROR: Stale serial for package mammoth
2015-07-16 04:42:08,561 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 04:42:08,561 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 05:42:03,721 ERROR: Stale serial for package mammoth
2015-07-16 05:42:03,721 ERROR: Stale serial for package mammoth
2015-07-16 05:42:05,720 ERROR: Stale serial for package mammoth
2015-07-16 05:42:05,720 ERROR: Stale serial for package mammoth
2015-07-16 05:42:08,719 ERROR: Stale serial for package mammoth
2015-07-16 05:42:08,719 ERROR: Stale serial for package mammoth
2015-07-16 05:42:08,722 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 05:42:08,722 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 06:42:03,641 ERROR: Stale serial for package mammoth
2015-07-16 06:42:03,641 ERROR: Stale serial for package mammoth
2015-07-16 06:42:05,672 ERROR: Stale serial for package mammoth
2015-07-16 06:42:05,672 ERROR: Stale serial for package mammoth
2015-07-16 06:42:08,705 ERROR: Stale serial for package mammoth
2015-07-16 06:42:08,705 ERROR: Stale serial for package mammoth
2015-07-16 06:42:08,707 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 06:42:08,707 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 07:42:04,477 ERROR: Stale serial for package mammoth
2015-07-16 07:42:04,477 ERROR: Stale serial for package mammoth
2015-07-16 07:42:06,480 ERROR: Stale serial for package mammoth
2015-07-16 07:42:06,480 ERROR: Stale serial for package mammoth
2015-07-16 07:42:09,155 ERROR: Stale serial for package mammoth
2015-07-16 07:42:09,155 ERROR: Stale serial for package mammoth
2015-07-16 07:42:09,158 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 07:42:09,158 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 08:42:04,061 ERROR: Stale serial for package mammoth
2015-07-16 08:42:04,061 ERROR: Stale serial for package mammoth
2015-07-16 08:42:06,090 ERROR: Stale serial for package mammoth
2015-07-16 08:42:06,090 ERROR: Stale serial for package mammoth
2015-07-16 08:42:09,121 ERROR: Stale serial for package mammoth
2015-07-16 08:42:09,121 ERROR: Stale serial for package mammoth
2015-07-16 08:42:09,123 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 08:42:09,123 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 09:43:06,504 ERROR: Error syncing package: ansi-colorprint@1634632
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-16 09:43:06,504 ERROR: Error syncing package: ansi-colorprint@1634632
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-16 09:43:09,026 ERROR: Error syncing package: mammoth@1634623
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-16 09:43:09,026 ERROR: Error syncing package: mammoth@1634623
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-16 09:43:09,033 ERROR: Error syncing package: n_e_s_t_e_r@1634575
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-16 09:43:09,030 ERROR: Error syncing package: Noober_Nester@1634572
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-16 09:43:09,033 ERROR: Error syncing package: n_e_s_t_e_r@1634575
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-16 09:43:09,030 ERROR: Error syncing package: Noober_Nester@1634572
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-16 10:42:04,239 ERROR: Stale serial for package mammoth
2015-07-16 10:42:04,239 ERROR: Stale serial for package mammoth
2015-07-16 10:42:06,275 ERROR: Stale serial for package mammoth
2015-07-16 10:42:06,275 ERROR: Stale serial for package mammoth
2015-07-16 10:42:09,305 ERROR: Stale serial for package mammoth
2015-07-16 10:42:09,305 ERROR: Stale serial for package mammoth
2015-07-16 10:42:09,307 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 10:42:09,307 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 11:42:04,082 ERROR: Stale serial for package mammoth
2015-07-16 11:42:04,082 ERROR: Stale serial for package mammoth
2015-07-16 11:42:06,108 ERROR: Stale serial for package mammoth
2015-07-16 11:42:06,108 ERROR: Stale serial for package mammoth
2015-07-16 11:42:09,135 ERROR: Stale serial for package mammoth
2015-07-16 11:42:09,135 ERROR: Stale serial for package mammoth
2015-07-16 11:42:09,137 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 11:42:09,137 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 12:42:04,249 ERROR: Stale serial for package mammoth
2015-07-16 12:42:04,249 ERROR: Stale serial for package mammoth
2015-07-16 12:42:06,274 ERROR: Stale serial for package mammoth
2015-07-16 12:42:06,274 ERROR: Stale serial for package mammoth
2015-07-16 12:42:09,274 ERROR: Stale serial for package mammoth
2015-07-16 12:42:09,274 ERROR: Stale serial for package mammoth
2015-07-16 12:42:09,276 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 12:42:09,276 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 13:42:03,903 ERROR: Stale serial for package mammoth
2015-07-16 13:42:03,903 ERROR: Stale serial for package mammoth
2015-07-16 13:42:05,966 ERROR: Stale serial for package mammoth
2015-07-16 13:42:05,966 ERROR: Stale serial for package mammoth
2015-07-16 13:42:08,986 ERROR: Stale serial for package mammoth
2015-07-16 13:42:08,986 ERROR: Stale serial for package mammoth
2015-07-16 13:42:08,989 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 13:42:08,989 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 14:42:03,754 ERROR: Stale serial for package mammoth
2015-07-16 14:42:03,754 ERROR: Stale serial for package mammoth
2015-07-16 14:42:05,757 ERROR: Stale serial for package mammoth
2015-07-16 14:42:05,757 ERROR: Stale serial for package mammoth
2015-07-16 14:42:08,759 ERROR: Stale serial for package mammoth
2015-07-16 14:42:08,759 ERROR: Stale serial for package mammoth
2015-07-16 14:42:08,761 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 14:42:08,761 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 15:42:05,149 ERROR: Stale serial for package mammoth
2015-07-16 15:42:05,149 ERROR: Stale serial for package mammoth
2015-07-16 15:42:07,190 ERROR: Stale serial for package mammoth
2015-07-16 15:42:07,190 ERROR: Stale serial for package mammoth
2015-07-16 15:42:10,523 ERROR: Stale serial for package mammoth
2015-07-16 15:42:10,523 ERROR: Stale serial for package mammoth
2015-07-16 15:42:10,525 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 15:42:10,525 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 16:42:04,455 ERROR: Stale serial for package mammoth
2015-07-16 16:42:04,455 ERROR: Stale serial for package mammoth
2015-07-16 16:42:06,459 ERROR: Stale serial for package mammoth
2015-07-16 16:42:06,459 ERROR: Stale serial for package mammoth
2015-07-16 16:42:09,464 ERROR: Stale serial for package mammoth
2015-07-16 16:42:09,464 ERROR: Stale serial for package mammoth
2015-07-16 16:42:09,466 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 16:42:09,466 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 17:42:03,715 ERROR: Stale serial for package mammoth
2015-07-16 17:42:03,715 ERROR: Stale serial for package mammoth
2015-07-16 17:42:05,719 ERROR: Stale serial for package mammoth
2015-07-16 17:42:05,719 ERROR: Stale serial for package mammoth
2015-07-16 17:42:08,725 ERROR: Stale serial for package mammoth
2015-07-16 17:42:08,725 ERROR: Stale serial for package mammoth
2015-07-16 17:42:08,727 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 17:42:08,727 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 18:42:03,896 ERROR: Stale serial for package mammoth
2015-07-16 18:42:03,896 ERROR: Stale serial for package mammoth
2015-07-16 18:42:05,908 ERROR: Stale serial for package mammoth
2015-07-16 18:42:05,908 ERROR: Stale serial for package mammoth
2015-07-16 18:42:08,922 ERROR: Stale serial for package mammoth
2015-07-16 18:42:08,922 ERROR: Stale serial for package mammoth
2015-07-16 18:42:08,924 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 18:42:08,924 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 19:42:03,736 ERROR: Stale serial for package mammoth
2015-07-16 19:42:03,736 ERROR: Stale serial for package mammoth
2015-07-16 19:42:05,757 ERROR: Stale serial for package mammoth
2015-07-16 19:42:05,757 ERROR: Stale serial for package mammoth
2015-07-16 19:42:08,779 ERROR: Stale serial for package mammoth
2015-07-16 19:42:08,779 ERROR: Stale serial for package mammoth
2015-07-16 19:42:08,781 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 19:42:08,781 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 20:42:11,740 ERROR: Error syncing package: mammoth@1634623
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/mammoth/json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x3fff7d1bd7d0>, 'Connection to pypi.python.org timed out. (connect timeout=10.0)'))
2015-07-16 20:42:11,740 ERROR: Error syncing package: mammoth@1634623
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/mammoth/json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x3fff7d1bd7d0>, 'Connection to pypi.python.org timed out. (connect timeout=10.0)'))
2015-07-16 21:42:03,726 ERROR: Stale serial for package mammoth
2015-07-16 21:42:03,726 ERROR: Stale serial for package mammoth
2015-07-16 21:42:05,730 ERROR: Stale serial for package mammoth
2015-07-16 21:42:05,730 ERROR: Stale serial for package mammoth
2015-07-16 21:42:08,733 ERROR: Stale serial for package mammoth
2015-07-16 21:42:08,733 ERROR: Stale serial for package mammoth
2015-07-16 21:42:08,736 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 21:42:08,736 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 22:42:03,645 ERROR: Stale serial for package mammoth
2015-07-16 22:42:03,645 ERROR: Stale serial for package mammoth
2015-07-16 22:42:05,677 ERROR: Stale serial for package mammoth
2015-07-16 22:42:05,677 ERROR: Stale serial for package mammoth
2015-07-16 22:42:08,712 ERROR: Stale serial for package mammoth
2015-07-16 22:42:08,712 ERROR: Stale serial for package mammoth
2015-07-16 22:42:08,714 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-16 22:42:08,714 ERROR: Stale serial for mammoth (1634623) not updating. Giving up.
2015-07-23 00:42:29,575 ERROR: Error syncing package: ka-lite@1645261
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-23 00:42:29,575 ERROR: Error syncing package: ka-lite@1645261
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-27 14:42:06,771 ERROR: Error syncing package: jubatus@1650974
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2015-07-27 14:42:06,771 ERROR: Error syncing package: jubatus@1650974
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 70, in sync
    '/pypi/{0}/json'.format(self.name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2015-07-28 00:42:14,517 ERROR: Stale serial for package tendenci
2015-07-28 00:42:14,517 ERROR: Stale serial for package tendenci
2015-07-28 00:43:32,451 ERROR: Error syncing package: tendenci@1651813
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-28 00:43:32,451 ERROR: Error syncing package: tendenci@1651813
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-28 02:43:46,196 ERROR: Error syncing package: ka-lite@1651972
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 200, in download_file
    for chunk in r.iter_content(chunk_size=64 * 1024):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib64/python2.7/httplib.py", line 567, in read
    s = self.fp.read(amt)
  File "/usr/lib64/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib64/python2.7/ssl.py", line 246, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 165, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer
2015-07-28 02:43:46,196 ERROR: Error syncing package: ka-lite@1651972
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 200, in download_file
    for chunk in r.iter_content(chunk_size=64 * 1024):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib64/python2.7/httplib.py", line 567, in read
    s = self.fp.read(amt)
  File "/usr/lib64/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib64/python2.7/ssl.py", line 246, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 165, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer
2015-07-29 00:42:31,511 ERROR: Error syncing package: wordfreq@1653599
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 200, in download_file
    for chunk in r.iter_content(chunk_size=64 * 1024):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 660, in generate
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
2015-07-29 00:42:31,511 ERROR: Error syncing package: wordfreq@1653599
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 200, in download_file
    for chunk in r.iter_content(chunk_size=64 * 1024):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 660, in generate
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
2015-07-29 02:42:18,479 ERROR: Error syncing package: dataone.generic_member_node@1653800
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-29 02:42:18,479 ERROR: Error syncing package: dataone.generic_member_node@1653800
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 78, in sync
    self.sync_release_files()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 109, in sync_release_files
    self.download_file(release_file['url'], release_file['md5_digest'])
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 197, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 43, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=10.0)
2015-07-29 02:42:18,954 ERROR: Stale serial for package snakebite
2015-07-29 02:42:18,954 ERROR: Stale serial for package snakebite
2015-07-29 02:42:21,967 ERROR: Stale serial for package snakebite
2015-07-29 02:42:21,967 ERROR: Stale serial for package snakebite
2015-07-31 17:42:07,619 ERROR: Error syncing package: smsowl@1658209
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 77, in sync
    self.fetch_simple_page()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 121, in fetch_simple_page
    '/simple/{0}/'.format(self.quoted_name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 44, in get
    r.raise_for_status()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
2015-07-31 17:42:07,619 ERROR: Error syncing package: smsowl@1658209
Traceback (most recent call last):
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 77, in sync
    self.fetch_simple_page()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/package.py", line 121, in fetch_simple_page
    '/simple/{0}/'.format(self.quoted_name), self.serial)
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/bandersnatch/master.py", line 44, in get
    r.raise_for_status()
  File "/www/mirrors/bin/bandersnatch/lib/python2.7/site-packages/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
2015-07-31 21:42:07,089 ERROR: Stale serial for package pytok
2015-07-31 21:42:07,089 ERROR: Stale serial for package pytok
2015-07-31 21:42:09,562 ERROR: Stale serial for package pytok
2015-07-31 21:42:09,562 ERROR: Stale serial for package pytok
2015-08-05 07:42:05,071 ERROR: Stale serial for package botocore
2015-08-05 07:42:05,071 ERROR: Stale serial for package botocore
2015-08-05 07:42:10,576 ERROR: Stale serial for package botocore
2015-08-05 07:42:10,576 ERROR: Stale serial for package botocore
2015-08-05 07:42:12,991 ERROR: Stale serial for package botocore
2015-08-05 07:42:12,991 ERROR: Stale serial for package botocore
2015-08-05 07:42:12,993 ERROR: Stale serial for botocore (1664526) not updating. Giving up.
2015-08-05 07:42:12,993 ERROR: Stale serial for botocore (1664526) not updating. Giving up.
2015-08-06 22:42:06,770 ERROR: Stale serial for package freezegun
2015-08-06 22:42:06,770 ERROR: Stale serial for package freezegun
